feat(protocol): add protocol option
mrzool/nordvpn-server-find pull request #7
Opened 2020-11-19 21:34 UTC by dmedinag

Allow the user to specify a protocol they want the server to support, between tcp and udp

Most but not all servers support these two protocols. This change makes the script a bit safer when scripting so that one can suffix appropriately with ".tcp" or ".udp" the nm connection to be used.

2020-11-22 16:16 UTC, mrzool reviewed
Not sure what to think about this one. On one side, you now make an additional HTTP request with every invocation of the script. Being HTTP requests the main bottleneck in there, the script now takes more than twice as long to run:

```
nordvpn-server-find(master)$ hyperfine "./nordvpn-server-find -l de"
Benchmark #1: ./nordvpn-server-find -l de
  Time (mean ± σ):      4.211 s ±  0.232 s    [User: 158.7 ms, System: 115.2 ms]
  Range (min … max):    3.823 s …  4.611 s    10 runs
 
nordvpn-server-find(master)$ git checkout protocol 
Switched to branch 'protocol'
nordvpn-server-find(protocol)$ hyperfine "./nordvpn-server-find -l de"
Benchmark #1: ./nordvpn-server-find -l de
  Time (mean ± σ):      8.574 s ±  0.264 s    [User: 466.2 ms, System: 202.7 ms]
  Range (min … max):    8.095 s …  8.962 s    10 runs
```

This is already a major red flag. In addition to that, what are the benefits of providing a protocol switch? Since the servers and their loads are exactly the same regardless of the protocol, switching protocol has no effect whatsoever on the output I get:

```
nordvpn-server-find(protocol)$ diff -s <(./nordvpn-server-find -l de) <(./nordvpn-server-find -l de -p udp)
Files /dev/fd/63 and /dev/fd/62 are identical
```

So we have an additional HTTP request plus an additional `jq` invocation — which effectively doubles the execution time of the script — but no additional information reported and no apparent benefit for the user as far as I can tell. Am I missing something?

2020-11-23 07:37 UTC, dmedinag commented
> you now make an additional HTTP request with every invocation of the script. Being HTTP requests the main bottleneck in there, the script now takes more than twice as long to run

I'm also very unhappy with this. I don't know if there's a way we can simplify the two queries into a single one, I didn't find it.

> what are the benefits of providing a protocol switch?

It's just annoying that some (and only some) servers do not support both protocols. This leads to errors when scripting the connection to a specific server considering only its load, and not the protocols it supports.

Any ideas on how to work around this?

2020-11-29 13:58 UTC, mrzool requested changes
Do you need both HTTP requests for the protocol switch to work?

In any case definitely move your `server_descriptions` request to its own option argument, as I do [here](https://github.com/mrzool/nordvpn-server-find/blob/c319ad4add9f8511123ff7a511f4e12121d7bf3b/nordvpn-server-find#L74) for the `-r` flag, so that the request gets triggered only when actually needed.

If that's sufficient for the protocol switch to work you can then exit right away and avoid the second request. If not, try to make it work without the second request. If that's really impossible, at least the script will work as fast as it did before in all invocations without the `-p` flag.

2020-12-03 20:47 UTC, dmedinag commented
Actually I'm not sure anymore that not all servers support all protocols, here's the problem I had and why I thought this was the right fix:
When triggering
```bash
nmcli connection up `nordvpn-server-find -r`.udp
```
I was most of the times getting an error saying 
```
Error: unknown connection '<connection name>.udp'.
```
I thought this was happening because the server `<connection name>` did not support udp, but it turned out that the issue was that the udp connection was not being recognized by `nmcli`.

Note that this happened even when I had properly imported the `<connection name>.udp` file (through `nmcli connection import`). However, I had loaded the whole 11K+ list of NordVPN connections (both udp and tcp), and **this seems to not be handled properly by NetworkManager**, at least not in my system.

I am unaware of any limits in the number of (VPN) connections that NetworkManager can have registered (they're in the end just files in `/etc/NetworkManager/system-connections`), but I seem to have found it. **If I only load the connections from the couple of countries that I usually connect from (roughly 1.3K), this problem vanishes.**

With all of this in mind, I'm inclined to remove this protocol flag all along and remove this poorly performing feature.

What do you think?

2020-12-16 21:11 UTC, mrzool commented
Really sorry about the delay, I've been _really_ busy. Let's close this for now and get back to it should you find out that such a feature is actually needed after all. As it stands, it's probably not worth the trouble.

2020-12-16 21:11 UTC, closed without merging