feat(quiet): add a -q flag to help scripting
mrzool/nordvpn-server-find pull request #8
Opened 2020-11-19 22:00 UTC by dmedinag

Add a quiet mode to print the best server for a specific location. Note
that this flag makes -n irrelevant, since it will always print a single
result.

Closes #6

2020-11-22 15:13 UTC, mrzool requested changes
This seems to be working well, but I'm not super happy with the wording of the help.

For example, for the `-n` flag, this is not exactly right: `defaults to 1 if -q is set, 20 otherwise`. The actual behavior is not that `-n` defaults to `1` when `-q` is given, but that `-n` *gets forcibly set* to `1` and that a manually set value is effectively ignored. Saying that a parameter *defaults to* a value gives the false impression that that value can get overridden by the user.

I would propose the following wording instead:

```
-r   recommended   just output the recommended server for your location and exit, ignoring other options
-q   quiet         just output the best result for the given location, ignoring the -n and the -c option
-l   location      2-letter ISO 3166-1 country code (ex: us, uk, de)
-c   capacity      current server load, integer between 1-100 (defaults to 30)
-n   limit         limits number of results, integer between 1-100 (defaults to 20)
```

What do you think?

2020-11-23 07:42 UTC, dmedinag commented
you're right! Updated in 4a01183, if you're happy with it I'll squash the commits.

2020-11-23 21:30 UTC, mrzool commented
Thanks! All that's left now is updating the readme, then I'll merge.

2020-11-24 14:35 UTC, dmedinag commented
Fair, done! :)

2020-11-24 15:23 UTC, mrzool commented
Wonderful, merging. I'll get back to you on the other PR as soon as I can.

2020-11-24 15:23 UTC, merged